language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt-cli
deploy:
  provider: script
  skip_cleanup: true
  script: grunt gh-pages
  on:
    tags: true
    repo: noflo/noflo-browser-app
