language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
after_success:
- grunt gh-pages
env:
  global:
    secure: gfD86/uZJ0QI1V9tM+W0jvn3XFm2xaW51Bi4tnwOvw2WDlcwQu8RVfm73OTYH2pOctNYyypOvccywIVoYAapxEhXv+J/2Pj+0NVJ5w/0vftxsE5idJIqCp9U2CmNb/Uc8K387T3cDNICORncjqfCyph7oXPoeZ+b7EK4lpEvTtc=
