language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
after_success:
- grunt gh-pages
env:
  global:
    secure: T2H7SFN56s6V50+V7bHYcKCw/aoh018SgPKM3RK9Cxf0PW7uVY7VzY8guU9i1MRQ2m6lgaFbwVyYJhquRAC+NGuC4sPAGxc1up8GpyO6uSOcjJlkD1ysjBrU1dBfj/DV3gxaFVjvpuL/WBMSYaKbQq4vARufPnkqOIAI8bec/4k=
